version: '3.9'

services:

  portainer:
    image: cr.portainer.io/portainer/portainer-ce:2.9.3
    container_name: portainer
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./datos:/data
      - /:/host
    restart: always

  # PORTAINER AGENT PERMITE GESTIONAR PARÁMETROS DEL HOST
    # docker run -d -p 9001:9001 --name portainer_agent --restart=always 
    # -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes:/var/lib/docker/volumes -v /:/host portainer/agent

  # portainer_agent:
  #   image: portainer/agent:latest
  #   container_name: portainer_agent
  #   ports:
  #     - 9001:9001
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/lib/docker/volumes:/var/lib/docker/volumes
  #     - /:/host
  #   restart: always
